#pragma once
#include <Windows.h>
#include "librarys.hpp"
#include "driver.hpp"
#include "settings.hpp"
#include "offsets.hpp"
#include "sdk.hpp"
#include "input.hpp"
#include "gui.hpp"
#include "game.hpp"